import http from './http.js'
export const tutorApi = {
  getProfile: () => http.get('/tutor/profile'),
  updateProfile: (data) => http.put('/tutor/profile', data),
  getDashboard: () => http.get('/tutor/dashboard'),
  getEducation: () => http.get('/tutor/education'),
  addEducation: (data) => http.post('/tutor/education', data),
  updateEducation: (id, data) => http.put(`/tutor/education/${id}`, data),
  deleteEducation: (id) => http.delete(`/tutor/education/${id}`),
  getPreferences: () => http.get('/tutor/preferences'),
  savePreferences: (data) => http.put('/tutor/preferences', data),
  getDocuments: () => http.get('/tutor/documents'),
  uploadDocument: (formData) => http.post('/tutor/documents', formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  deleteDocument: (id) => http.delete(`/tutor/documents/${id}`),
  getChangeRequest: () => http.get('/tutor/change-request'),
  submitChangeRequest: (data) => http.post('/tutor/change-request', data),
  cancelChangeRequest: () => http.delete('/tutor/change-request'),
  doneEditing: () => http.put('/tutor/change-request/done'),
  getPersonalInfo: () => http.get('/tutor/personal-info'),
  savePersonalInfo: (data) => http.put('/tutor/personal-info', data),
  getVideos: () => http.get('/tutor/videos'),
  uploadVideo: (formData, config = {}) => http.post('/tutor/videos', formData, { headers: { 'Content-Type': 'multipart/form-data' }, ...config }),
  updateVideo: (id, data) => http.put(`/tutor/videos/${id}`, data),
  deleteVideo: (id) => http.delete(`/tutor/videos/${id}`),
  getTravel: () => http.get('/tutor/travel'),
  addTravel: (data) => http.post('/tutor/travel', data),
  updateTravel: (id, data) => http.put(`/tutor/travel/${id}`, data),
  deleteTravel: (id) => http.delete(`/tutor/travel/${id}`),
}
