<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UniversitySeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('universities')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $universities = [
            // ── Public Universities ──────────────────────────────────────────
            // General
            ['name' => 'University of Dhaka',                                      'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'Jahangirnagar University',                                  'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'Jagannath University',                                       'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'Bangladesh University of Professionals',                     'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'Bangladesh University of Engineering & Technology',          'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'Military Institute of Science and Technology',               'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'Sher-e-Bangla Agricultural University',                      'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'Bangladesh Medical University',                              'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'Bangladesh University of Textiles',                          'district' => 'Dhaka',          'type' => 'public'],
            ['name' => 'University of Rajshahi',                                    'district' => 'Rajshahi',       'type' => 'public'],
            ['name' => 'Rajshahi University of Engineering & Technology',            'district' => 'Rajshahi',       'type' => 'public'],
            ['name' => 'Rajshahi Medical University',                               'district' => 'Rajshahi',       'type' => 'public'],
            ['name' => 'University of Chittagong',                                  'district' => 'Chattogram',     'type' => 'public'],
            ['name' => 'Chittagong University of Engineering & Technology',          'district' => 'Chattogram',     'type' => 'public'],
            ['name' => 'Chittagong Medical University',                             'district' => 'Chattogram',     'type' => 'public'],
            ['name' => 'Chittagong Veterinary and Animal Sciences University',       'district' => 'Chattogram',     'type' => 'public'],
            ['name' => 'Bangladesh Maritime University',                             'district' => 'Chattogram',     'type' => 'public'],
            ['name' => 'Islamic University, Bangladesh',                             'district' => 'Kushtia',        'type' => 'public'],
            ['name' => 'Khulna University',                                         'district' => 'Khulna',         'type' => 'public'],
            ['name' => 'Khulna University of Engineering & Technology',             'district' => 'Khulna',         'type' => 'public'],
            ['name' => 'Khulna Agricultural University',                            'district' => 'Khulna',         'type' => 'public'],
            ['name' => 'Khulna Medical University',                                 'district' => 'Khulna',         'type' => 'public'],
            ['name' => 'Shahjalal University of Science and Technology',             'district' => 'Sylhet',         'type' => 'public'],
            ['name' => 'Sylhet Agricultural University',                            'district' => 'Sylhet',         'type' => 'public'],
            ['name' => 'Sylhet Medical University',                                 'district' => 'Sylhet',         'type' => 'public'],
            ['name' => 'Comilla University',                                        'district' => 'Cumilla',        'type' => 'public'],
            ['name' => 'Jatiya Kabi Kazi Nazrul Islam University',                  'district' => 'Mymensingh',     'type' => 'public'],
            ['name' => 'Bangladesh Agricultural University',                        'district' => 'Mymensingh',     'type' => 'public'],
            ['name' => 'Begum Rokeya University',                                   'district' => 'Rangpur',        'type' => 'public'],
            ['name' => 'University of Barisal',                                     'district' => 'Barishal',       'type' => 'public'],
            ['name' => 'Rabindra University, Bangladesh',                           'district' => 'Sirajganj',      'type' => 'public'],
            ['name' => 'Netrokona University',                                      'district' => 'Netrokona',      'type' => 'public'],
            ['name' => 'Kishoreganj University',                                    'district' => 'Kishoreganj',    'type' => 'public'],
            ['name' => 'Meherpur University',                                       'district' => 'Meherpur',       'type' => 'public'],
            ['name' => 'Thakurgaon University',                                     'district' => 'Thakurgaon',     'type' => 'public'],
            ['name' => 'Hajee Mohammad Danesh Science & Technology University',      'district' => 'Dinajpur',       'type' => 'public'],
            ['name' => 'Mawlana Bhashani Science and Technology University',         'district' => 'Tangail',        'type' => 'public'],
            ['name' => 'Patuakhali Science and Technology University',               'district' => 'Patuakhali',     'type' => 'public'],
            ['name' => 'Noakhali Science and Technology University',                 'district' => 'Noakhali',       'type' => 'public'],
            ['name' => 'Jashore University of Science and Technology',               'district' => 'Jashore',        'type' => 'public'],
            ['name' => 'Pabna University of Science and Technology',                 'district' => 'Pabna',          'type' => 'public'],
            ['name' => 'Gopalganj Science and Technology University',                'district' => 'Gopalganj',      'type' => 'public'],
            ['name' => 'Rangamati Science and Technology University',                'district' => 'Rangamati',      'type' => 'public'],
            ['name' => 'Jamalpur Science and Technology University',                 'district' => 'Jamalpur',       'type' => 'public'],
            ['name' => 'Chandpur Science and Technology University',                 'district' => 'Chandpur',       'type' => 'public'],
            ['name' => 'Sunamganj Science and Technology University',                'district' => 'Sunamganj',      'type' => 'public'],
            ['name' => 'Bogura Science and Technology University',                   'district' => 'Bogura',         'type' => 'public'],
            ['name' => 'Lakshmipur Science and Technology University',               'district' => 'Lakshmipur',     'type' => 'public'],
            ['name' => 'Pirojpur Science and Technology University',                 'district' => 'Pirojpur',       'type' => 'public'],
            ['name' => 'Satkhira University of Science and Technology',              'district' => 'Satkhira',       'type' => 'public'],
            ['name' => 'Narayanganj Science and Technology University',              'district' => 'Narayanganj',    'type' => 'public'],
            ['name' => 'Dhaka University of Engineering & Technology',              'district' => 'Gazipur',        'type' => 'public'],
            ['name' => 'Gazipur Agricultural University',                           'district' => 'Gazipur',        'type' => 'public'],
            ['name' => 'University of Frontier Technology, Bangladesh',              'district' => 'Gazipur',        'type' => 'public'],
            ['name' => 'Habiganj Agricultural University',                          'district' => 'Habiganj',       'type' => 'public'],
            ['name' => 'Kurigram Agricultural University',                          'district' => 'Kurigram',       'type' => 'public'],
            ['name' => 'Shariatpur Agriculture University',                         'district' => 'Shariatpur',     'type' => 'public'],
            ['name' => 'Aviation and Aerospace University Bangladesh',               'district' => 'Lalmonirhat',    'type' => 'public'],

            // ── Private Universities ─────────────────────────────────────────
            ['name' => 'North South University',                                    'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Brac University',                                           'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'American International University-Bangladesh',              'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'East West University',                                      'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Daffodil International University',                         'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'United International University',                           'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'University of Liberal Arts Bangladesh',                     'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Independent University, Bangladesh',                        'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Southeast University',                                      'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Stamford University Bangladesh',                            'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Green University of Bangladesh',                            'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'University of Asia Pacific (Bangladesh)',                   'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Notre Dame University Bangladesh',                          'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Ahsanullah University of Science and Technology',           'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Dhaka International University',                            'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'State University of Bangladesh',                            'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Northern University, Bangladesh',                           'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Manarat International University',                          'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Prime University',                                          'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Eastern University, Bangladesh',                            'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Bangladesh University',                                     'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'City University, Bangladesh',                               'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Primeasia University',                                      'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Royal University of Dhaka',                                 'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Uttara University',                                         'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'World University of Bangladesh',                            'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Gono Bishwabidyalay',                                       'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Asian University of Bangladesh',                            'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'People\'s University of Bangladesh',                        'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Bangladesh University of Business and Technology',          'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Atish Dipankar University of Science and Technology',       'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Central University of Science and Technology',              'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Central Women\'s University',                               'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Shanto-Mariam University of Creative Technology',           'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'BGMEA University of Fashion & Technology',                  'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'University of Development Alternative',                     'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Grameen University',                                        'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Sonargaon University',                                      'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Fareast International University',                          'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Bangladesh Islami University',                              'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Canadian University of Bangladesh',                         'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'University of Scholars',                                    'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Anwer Khan Modern University',                              'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Victoria University of Bangladesh',                         'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'European University of Bangladesh',                         'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'International University of Business Agriculture and Technology', 'district' => 'Dhaka',    'type' => 'private'],
            ['name' => 'Millennium University',                                     'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Queens University',                                         'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Presidency University',                                     'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Asa University Bangladesh',                                 'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'IBAIS University',                                          'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'International Standard University',                         'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'ZNRF University of Management Sciences',                    'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'International Islami University of Science and Technology Bangladesh', 'district' => 'Dhaka', 'type' => 'private'],
            ['name' => 'Microland University of Science and Technology',            'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Bangladesh University of Health Sciences',                  'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'Tagore University of Creative Arts',                        'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'University of South Asia, Bangladesh',                      'district' => 'Dhaka',          'type' => 'private'],
            ['name' => 'International Islamic University, Chittagong',              'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'Chittagong Independent University',                         'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'BGC Trust University Bangladesh',                           'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'Premier University, Chittagong',                            'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'Southern University, Bangladesh',                           'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'East Delta University',                                     'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'Port City International University',                        'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'University of Creative Technology Chittagong',              'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'University of Science & Technology Chittagong',             'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'University of Information Technology and Sciences',         'district' => 'Chattogram',     'type' => 'private'],
            ['name' => 'Sylhet International University',                           'district' => 'Sylhet',         'type' => 'private'],
            ['name' => 'Leading University',                                        'district' => 'Sylhet',         'type' => 'private'],
            ['name' => 'Metropolitan University',                                   'district' => 'Sylhet',         'type' => 'private'],
            ['name' => 'North East University Bangladesh',                          'district' => 'Sylhet',         'type' => 'private'],
            ['name' => 'RTM Al-Kabir Technical University',                         'district' => 'Sylhet',         'type' => 'private'],
            ['name' => 'Northern University of Business and Technology Khulna',     'district' => 'Khulna',         'type' => 'private'],
            ['name' => 'North Western University, Bangladesh',                      'district' => 'Khulna',         'type' => 'private'],
            ['name' => 'Bangladesh Army University of Science & Technology, Khulna', 'district' => 'Khulna',       'type' => 'private'],
            ['name' => 'Khulna Khan Bahadur Ahsanullah University',                'district' => 'Khulna',         'type' => 'private'],
            ['name' => 'Varendra University',                                       'district' => 'Rajshahi',       'type' => 'private'],
            ['name' => 'North Bengal International University',                     'district' => 'Rajshahi',       'type' => 'private'],
            ['name' => 'Britannia University',                                      'district' => 'Cumilla',        'type' => 'private'],
            ['name' => 'Bangladesh Army International University of Science & Technology', 'district' => 'Cumilla', 'type' => 'private'],
            ['name' => 'CCN University of Science & Technology',                    'district' => 'Cumilla',        'type' => 'private'],
            ['name' => 'Feni University',                                           'district' => 'Feni',           'type' => 'private'],
            ['name' => 'Khwaja Yunus Ali University',                               'district' => 'Sirajganj',      'type' => 'private'],
            ['name' => 'First Capital University Of Bangladesh',                    'district' => 'Chuadanga',      'type' => 'private'],
            ['name' => 'Hamdard University Bangladesh',                             'district' => 'Munshiganj',     'type' => 'private'],
            ['name' => 'Ishakha International University',                          'district' => 'Kishoreganj',    'type' => 'private'],
            ['name' => 'Dr. Momtaz Begum University of Science and Technology',     'district' => 'Kishoreganj',    'type' => 'private'],
            ['name' => 'Cox\'s Bazar International University',                    'district' => "Cox's Bazar",    'type' => 'private'],
            ['name' => 'German University Bangladesh',                              'district' => 'Gazipur',        'type' => 'private'],
            ['name' => 'Ranada Prasad Shaha University',                            'district' => 'Narayanganj',    'type' => 'private'],
            ['name' => 'University of Skill Enrichment and Technology',             'district' => 'Narayanganj',    'type' => 'private'],
            ['name' => 'Brahmaputra International University',                      'district' => 'Jamalpur',       'type' => 'private'],
            ['name' => 'Times University Bangladesh',                               'district' => 'Faridpur',       'type' => 'private'],
            ['name' => 'Global University Bangladesh',                              'district' => 'Barishal',       'type' => 'private'],
            ['name' => 'University of Global Village',                              'district' => 'Barishal',       'type' => 'private'],
            ['name' => 'Trust University, Barishal',                                'district' => 'Barishal',       'type' => 'private'],
            ['name' => 'NPI University of Bangladesh',                              'district' => 'Manikganj',      'type' => 'private'],
            ['name' => 'Rabindra Maitree University',                               'district' => 'Kushtia',        'type' => 'private'],
            ['name' => 'Lalon University of Science & Arts',                        'district' => 'Kushtia',        'type' => 'private'],
            ['name' => 'University of Brahmanbaria',                                'district' => 'Brahmanbaria',   'type' => 'private'],
            ['name' => 'ZH Sikder University of Science & Technology',              'district' => 'Shariatpur',     'type' => 'private'],
            ['name' => 'Bandarban University',                                      'district' => 'Bandarban',      'type' => 'private'],
            ['name' => 'Pundra University of Science and Technology',               'district' => 'Bogura',         'type' => 'private'],
            ['name' => 'Rajshahi Science & Technology University',                  'district' => 'Natore',         'type' => 'private'],
            ['name' => 'Bangladesh Army University of Science and Technology, Saidpur', 'district' => 'Nilphamari', 'type' => 'private'],
            ['name' => 'Exim Bank Agricultural University Bangladesh',              'district' => 'Chapainawabganj', 'type' => 'private'],
            ['name' => 'Bangladesh Army University of Engineering & Technology',    'district' => 'Natore',         'type' => 'private'],
        ];

        DB::table('universities')->insert($universities);
    }
}
